# Generated by Django 4.1.1 on 2022-12-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(default='个人练习生1号', max_length=10, verbose_name='用户昵称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_saying',
            field=models.CharField(default='这个练习生很懒，什么也没有写', max_length=250, verbose_name='用户个性签名'),
        ),
    ]
