# Generated by Django 4.1.1 on 2022-12-12 20:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Information',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False, verbose_name='专辑id')),
                ('album_name', models.CharField(max_length=30, verbose_name='专辑名称')),
                ('album_coverpage_pattern', models.CharField(choices=[(1, 'Simple'), (2, 'Bright'), (3, 'Dim')], max_length=10, verbose_name='专辑封面设计方式')),
                ('album_music_num', models.IntegerField(verbose_name='专辑包含歌曲数量')),
                ('album_created_time', models.DateField(verbose_name='专辑创建时间')),
                ('album_popularity', models.IntegerField(verbose_name='专辑热度')),
            ],
            options={
                'db_table': 'album_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment_Information',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('comment_theme', models.CharField(max_length=100, verbose_name='评论主题')),
                ('comment_grade', models.CharField(choices=[(1, 'Positive'), (2, 'Normal'), (3, 'Negative')], max_length=10, verbose_name='评论基调')),
                ('comment_content', models.CharField(max_length=10000, verbose_name='评论内容')),
            ],
            options={
                'db_table': 'comment_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback_Information',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False, verbose_name='回帖id')),
                ('feedback_theme', models.CharField(max_length=100, verbose_name='回帖主题')),
                ('feedback_time', models.DateField(verbose_name='回帖时间')),
                ('feedback_content', models.CharField(max_length=10000, verbose_name='回帖内容')),
            ],
            options={
                'db_table': 'feedback_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Music_Information',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('music_name', models.CharField(max_length=32, verbose_name='歌曲名称')),
                ('music_singing_type', models.CharField(choices=[(1, 'solo'), (2, 'antiphon'), (3, 'chorus')], max_length=10, verbose_name='歌曲演唱形式')),
                ('music_theme', models.CharField(choices=[(1, 'History'), (2, 'Anecdote'), (3, 'Emotion'), (4, 'Game'), (5, 'Encouragement'), (6, 'Nation'), (7, 'Other')], max_length=20, verbose_name='歌曲主题')),
                ('music_duration', models.DateTimeField(verbose_name='歌曲时长')),
                ('music_popularity', models.IntegerField(verbose_name='歌曲流行度')),
            ],
            options={
                'db_table': 'music_platform_database',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Singer_Information',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌手id')),
                ('singer_name', models.CharField(max_length=10, verbose_name='歌手姓名')),
                ('singer_nationality', models.CharField(choices=[(1, 'China'), (2, 'USA'), (3, 'UK'), (4, 'Japan'), (5, 'France'), (6, 'Germany'), (7, 'Koera'), (8, 'Russia'), (9, 'Italy'), (10, 'Spain'), (11, 'Australia'), (12, 'Canada')], max_length=10, verbose_name='歌手国籍')),
                ('singer_age', models.IntegerField(verbose_name='歌手年龄')),
                ('singer_sex', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10, verbose_name='歌手性别')),
                ('singer_popularity', models.IntegerField(verbose_name='歌手热度')),
                ('singer_debut_time', models.DateField(verbose_name='歌手出道时间')),
            ],
            options={
                'db_table': 'singer_information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Songsheet_Information',
            fields=[
                ('songsheet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Songsheet Id')),
                ('songsheet_name', models.CharField(max_length=32, verbose_name='Songsheet Name')),
                ('songsheet_music_num', models.IntegerField(default=0, verbose_name='Songsheet Volume')),
            ],
            options={
                'db_table': 'Songsheet_Information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Songsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='创建时间')),
                ('update_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='更新时间')),
                ('songsheet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.songsheet_information', verbose_name='Songsheet')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'User_Songsheet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='用户关注该歌手的时间')),
                ('singer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.singer_information')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_singer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='关注时间')),
                ('user_1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to=settings.AUTH_USER_MODEL, verbose_name='用户1')),
                ('user_2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to=settings.AUTH_USER_MODEL, verbose_name='用户2')),
            ],
            options={
                'db_table': 'user_relationship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_times', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='用户收藏歌曲的时间')),
                ('run_times', models.IntegerField(default=0, verbose_name='用户播放歌曲的次数')),
                ('music', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.music_information')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_music',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Feedback_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='回帖时间')),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.comment_information')),
                ('feedback', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.feedback_information')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feedback_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Comment_Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='评论时间')),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.comment_information')),
                ('target_singer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.singer_information')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_comment_singer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Comment_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='评论时间')),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.comment_information')),
                ('target_music', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.music_information')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_comment_music',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Songsheet_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='歌曲加入歌单的时间')),
                ('music', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.music_information')),
                ('songsheet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.songsheet_information')),
            ],
            options={
                'db_table': 'songsheet_music',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Singer_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='演唱时间')),
                ('music', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.music_information')),
                ('singer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.singer_information')),
            ],
            options={
                'db_table': 'singer_music',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Singer_Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.album_information')),
                ('singer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.singer_information')),
            ],
            options={
                'db_table': 'singer_album',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Album_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateField(default=datetime.date(2022, 12, 12), verbose_name='歌曲加入专辑的时间')),
                ('album', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.album_information')),
                ('music', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musics.music_information')),
            ],
            options={
                'db_table': 'album_music',
                'managed': True,
            },
        ),
    ]
