# Generated by Django 4.1.1 on 2022-12-19 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer_Write_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_time', models.DateField(default=datetime.date(2022, 12, 19), verbose_name='出版时间')),
            ],
        ),
        migrations.CreateModel(
            name='User_Become_Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.singer_information', verbose_name='歌手账号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
        ),
        migrations.AlterModelOptions(
            name='music_information',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback_information',
            name='feedback_time',
        ),
        migrations.RemoveField(
            model_name='songsheet_information',
            name='songsheet_music_num',
        ),
        migrations.RemoveField(
            model_name='user_comment_music',
            name='comment_time',
        ),
        migrations.RemoveField(
            model_name='user_comment_singer',
            name='comment_time',
        ),
        migrations.AddField(
            model_name='comment_information',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 11, 8, 54, 172399), verbose_name='评论时间'),
        ),
        migrations.AddField(
            model_name='music_information',
            name='music_link',
            field=models.CharField(default='http://ws.stream.qqmusic.qq.com/C400003UkWuI0E8U0l.m4a?guid=472740677&vkey=E3E33D1B7EEEC9C30F9D1F0E42E27F00CB92E8515BC8442E617ACEF1F646C6F9DD9397DD7DBED4300B1A044D27237FFD76D00883AB7FE62B&uin=&fromtag=120032', max_length=1000, verbose_name='播放链接'),
        ),
        migrations.AddField(
            model_name='music_information',
            name='music_public_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='歌曲创作时间'),
        ),
        migrations.AlterField(
            model_name='album_music',
            name='join_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='歌曲加入专辑的时间'),
        ),
        migrations.AlterField(
            model_name='music_information',
            name='music_duration',
            field=models.TimeField(verbose_name='歌曲时长'),
        ),
        migrations.AlterField(
            model_name='singer_music',
            name='sing_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='演唱时间'),
        ),
        migrations.AlterField(
            model_name='songsheet_music',
            name='join_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='歌曲加入歌单的时间'),
        ),
        migrations.AlterField(
            model_name='user_feedback_comment',
            name='feedback_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='回帖时间'),
        ),
        migrations.AlterField(
            model_name='user_music',
            name='store_times',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='用户收藏歌曲的时间'),
        ),
        migrations.AlterField(
            model_name='user_singer',
            name='attention_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='用户关注该歌手的时间'),
        ),
        migrations.AlterField(
            model_name='user_songsheet',
            name='create_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user_songsheet',
            name='update_time',
            field=models.DateField(default=datetime.date(2022, 12, 19), verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='music_information',
            table=None,
        ),
        migrations.DeleteModel(
            name='User_Relationship',
        ),
        migrations.AddField(
            model_name='singer_write_music',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music_information', verbose_name='歌曲'),
        ),
        migrations.AddField(
            model_name='singer_write_music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.singer_information', verbose_name='创作者'),
        ),
    ]
