# Generated by Django 4.1.1 on 2022-12-20 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_singer_write_music_user_become_singer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_music',
            name='join_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='歌曲加入专辑的时间'),
        ),
        migrations.AlterField(
            model_name='comment_information',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 21, 9, 24, 509988), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='music_information',
            name='music_popularity',
            field=models.IntegerField(default=0, verbose_name='歌曲流行度'),
        ),
        migrations.AlterField(
            model_name='music_information',
            name='music_public_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='歌曲创作时间'),
        ),
        migrations.AlterField(
            model_name='singer_information',
            name='singer_debut_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='歌手出道时间'),
        ),
        migrations.AlterField(
            model_name='singer_information',
            name='singer_popularity',
            field=models.IntegerField(default=0, verbose_name='歌手热度'),
        ),
        migrations.AlterField(
            model_name='singer_music',
            name='sing_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='演唱时间'),
        ),
        migrations.AlterField(
            model_name='singer_write_music',
            name='public_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='songsheet_music',
            name='join_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='歌曲加入歌单的时间'),
        ),
        migrations.AlterField(
            model_name='user_feedback_comment',
            name='feedback_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='回帖时间'),
        ),
        migrations.AlterField(
            model_name='user_music',
            name='store_times',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='用户收藏歌曲的时间'),
        ),
        migrations.AlterField(
            model_name='user_singer',
            name='attention_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='用户关注该歌手的时间'),
        ),
        migrations.AlterField(
            model_name='user_songsheet',
            name='create_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user_songsheet',
            name='update_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='更新时间'),
        ),
    ]
