# Generated by Django 4.1.1 on 2022-12-20 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_alter_album_music_join_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_information',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 21, 33, 40, 559605), verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='music_information',
            name='music_duration',
            field=models.IntegerField(default=3, verbose_name='歌曲时长'),
        ),
    ]
