# Generated by Django 4.1.1 on 2022-12-20 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_comment_information_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_information',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 21, 50, 53, 922996), verbose_name='评论时间'),
        ),
    ]
