# Generated by Django 4.1.1 on 2022-12-20 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_alter_comment_information_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_information',
            name='album_created_time',
            field=models.DateField(default=datetime.date(2022, 12, 20), verbose_name='专辑创建时间'),
        ),
        migrations.AlterField(
            model_name='album_information',
            name='album_music_num',
            field=models.IntegerField(default=0, verbose_name='专辑包含歌曲数量'),
        ),
        migrations.AlterField(
            model_name='album_information',
            name='album_popularity',
            field=models.IntegerField(default=0, verbose_name='专辑热度'),
        ),
        migrations.AlterField(
            model_name='comment_information',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 22, 50, 39, 375575), verbose_name='评论时间'),
        ),
    ]
